local p = require("gentleman_kanagawa_blur.palette")

return {
	NotifyBackground = { fg = p.fg, bg = p.bg_dark },
	NotifyERRORBorder = { fg = p.orange, bg = p.bg_dark },
	NotifyWARNBorder = { fg = p.yellow, bg = p.bg_dark },
	NotifyINFOBorder = { fg = p.purple, bg = p.bg_dark },
	NotifyDEBUGBorder = { fg = p.subtext1, bg = p.bg_dark },
	NotifyTRACEBorder = { fg = p.red, bg = p.bg_dark },
	NotifyERRORIcon = { fg = p.bright_orange },
	NotifyWARNIcon = { fg = p.bright_yellow },
	NotifyINFOIcon = { fg = p.bright_purple },
	NotifyDEBUGIcon = { fg = p.subtext4 },
	NotifyTRACEIcon = { fg = p.bright_red },
	NotifyERRORTitle = { fg = p.bright_orange },
	NotifyWARNTitle = { fg = p.bright_yellow },
	NotifyINFOTitle = { fg = p.bright_purple },
	NotifyDEBUGTitle = { fg = p.subtext4 },
	NotifyTRACETitle = { fg = p.bright_red },
	NotifyERRORBody = { fg = p.fg, bg = p.bg_dark },
	NotifyWARNBody = { fg = p.fg, bg = p.bg_dark },
	NotifyINFOBody = { fg = p.fg, bg = p.bg_dark },
	NotifyDEBUGBody = { fg = p.fg, bg = p.bg_dark },
	NotifyTRACEBody = { fg = p.fg, bg = p.bg_dark },
}
